### ISSUE TITLE
Red blinking in unity window when loading a scene from the scene library

### ISSUE THREAD

**Issue by vinayakagarwal4** [threedworld-mit/tdw#489] opened 2022-08-22 22:05 UTC
OSx module version 1.10.4

**Comment by alters-mit** [comment] 2022-08-25 12:59
Closing this issue. Not a bug; this is just what the build looks like on OSX before a camera is added.

**Comment by alters-mit** [comment] 2022-08-26 18:42
@vinayakagarwal4 Send your controller, the Player log, and your OS version.

**Closed** 2023-06-09 19:55 UTC
