### ISSUE TITLE
Processed ShapeNet Record

### ISSUE THREAD

**Issue by normster** [threedworld-mit/tdw#28] opened 2020-08-17 06:58 UTC
Hi,

The ShapeNet processing script is currently only compatible with Windows. Would it be possible to release the processed records or add linux/mac compatibility?

Thanks!

**Comment by alters-mit** [comment] 2020-08-17 20:11
@normster 

> Would it be possible to release the processed records

The records I used to create the dataset aren't that useful. To save on time, I created binaries that are only compatible with Windows and I skipped running V-HACD, a slow process that only matters for generating physics colliders (which were irrelevant to the dataset)

>or add linux/mac compatibility?

OS X compatibility is potentially a small task; if so, we can have this ready very soon. Linux compatibility is a large task because it requires upgrading TDW's Unity engine (which we've started, but we'll need to do a lot more testing before it's ready).

**Comment by normster** [comment] 2020-08-18 19:43
Thanks for the info! Is there any way I can help with adding macOS compatibility?

**Comment by alters-mit** [comment] 2020-08-19 19:59
@normster I opened this PR that you could help with: https://github.com/threedworld-mit/tdw/pulls

I don't have a Mac so I'm not sure all the binaries work. In particular, I'm skeptical about V-HACD. It would be very helpful it you could:

1. Run the test described in the PR. 
2. Attach the console output as a comment on this thread.
3. If the test crashes when trying to run V-HACD, try running this: https://github.com/kmammou/v-hacd/blob/master/install/run.py and attach the resulting binary to a comment on this thread.

**Comment by normster** [comment] 2020-08-19 20:08
Sure thing! I followed the instructions and got the following error when running the python script:

```
(base) ➜  example_controllers git:(asset_bundle_creator_osx) python3 local_object.py
Creating: /Users/normanmu/asset_bundle_creator
Traceback (most recent call last):
  File "local_object.py", line 45, in <module>
    LocalObject.run()
  File "local_object.py", line 18, in run
    asset_bundle_paths, record_path = AssetBundleCreator().create_asset_bundle("cube.fbx", True, 123, "", 1)
  File "/Users/normanmu/code/tdw/Python/tdw/asset_bundle_creator.py", line 68, in __init__
    self.project_path = self.get_unity_project()
  File "/Users/normanmu/code/tdw/Python/tdw/asset_bundle_creator.py", line 243, in get_unity_project
    call([str(AssetBundleCreator.get_editor_path().resolve()),
  File "/Users/normanmu/code/tdw/Python/tdw/asset_bundle_creator.py", line 190, in get_editor_path
    assert editor_path.exists(), f"Unity Hub not found."
AssertionError: Unity Hub not found.
```

So then I installed Unity Hub but I'm getting the same error. Am I missing some requirement?

**Comment by alters-mit** [comment] 2020-08-19 20:43
You need to also download Unity 2019.2.21f1 via Unity Hub (sorry for not mentioning that).

**Comment by normster** [comment] 2020-08-19 23:36
I installed Unity as well as assimp with `brew install assimp` and am having some issues with V-HACD now:

```
(base) ➜  example_controllers git:(asset_bundle_creator_osx) ✗ python3 local_object.py
Converting a .fbx file to .obj
Running V-HACD on a .obj file (this might take awhile).
dyld: Symbol not found: __ZTTNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEE
  Referenced from: /Users/normanmu/code/tdw/Python/tdw/binaries/Darwin/vhacd/testVHACD_github_no_ocl_omp
  Expected in: /usr/lib/libstdc++.6.dylib
 in /Users/normanmu/code/tdw/Python/tdw/binaries/Darwin/vhacd/testVHACD_github_no_ocl_omp
Traceback (most recent call last):
  File "local_object.py", line 45, in <module>
    LocalObject.run()
  File "local_object.py", line 18, in run
    asset_bundle_paths, record_path = AssetBundleCreator().create_asset_bundle("cube.fbx", True, 123, "", 1)
  File "/Users/normanmu/code/tdw/Python/tdw/asset_bundle_creator.py", line 93, in create_asset_bundle
    wrl_path = self.obj_to_wrl(model_path)
  File "/Users/normanmu/code/tdw/Python/tdw/asset_bundle_creator.py", line 345, in obj_to_wrl
    assert Path(wrl_filename).exists(), "Failed to create .wrl file. " \
AssertionError: Failed to create .wrl file. Check your original file to make sure that is 3D (not just a flat plane) and isn't corrupted.
```

**Comment by normster** [comment] 2020-08-20 02:48
It looks like the testVHACD binary needed to be rebuilt. I rebuilt it from the source at https://github.com/kmammou/v-hacd. I also had to disable OpenMP for now since there seems to be some issue with default clang I need to debug: https://iscinumpy.gitlab.io/post/omp-on-high-sierra/

```
git clone 
cd build/mac
cmake -D NO_OPENMP=ON -G Xcode ../../src
cmake --build .
```

Then I copied the output binary in `./test/Debug/testVHACD` over to `tdw/Python/tdw/binaries/Darwin/vhacd/testVHACD`. Also, at some point I had to manually create the `asset_bundle_creator` directories, I think `mkdir -p /asset_bundle_creator/Assets/Resources/` is enough.

Now I'm getting the following error instead:

```
(base) ➜  example_controllers git:(asset_bundle_creator_osx) ✗ python3 local_object.py
Converting a .fbx file to .obj
Running V-HACD on a .obj file (this might take awhile).
Created: cube.wrl
Removed V-HACD log file.
Removed superfluous .obj file: cube.obj
Converting .wrl to .obj
Created /Users/normanmu/code/tdw/Python/example_controllers/cube_colliders.obj from .wrl file.
Copying files into the Unity project.
Copied files into the Unity project.
Creating the prefab...
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
/Users/normanmu/asset_bundle_creator/Assets/Resources/prefab/cube.prefab
Traceback (most recent call last):
  File "local_object.py", line 45, in <module>
    LocalObject.run()
  File "local_object.py", line 18, in run
    asset_bundle_paths, record_path = AssetBundleCreator().create_asset_bundle("cube.fbx", True, 123, "", 1)
  File "/Users/normanmu/code/tdw/Python/tdw/asset_bundle_creator.py", line 96, in create_asset_bundle
    prefab_path, report_path = self.create_prefab(f"{model_name}_colliders.obj", model_name, model_path.suffix)
  File "/Users/normanmu/code/tdw/Python/tdw/asset_bundle_creator.py", line 487, in create_prefab
    assert prefab_path.exists(), "Failed to create prefab."
AssertionError: Failed to create prefab.
```

It looks like the called `create_prefab` command fails silently: 

```
(base) ➜  example_controllers git:(asset_bundle_creator_osx) ✗ /Applications/Unity/Hub/Editor/2019.2.21f1/Unity.app/Contents/MacOS/Unity -projectpath /Users/normanmu/asset_bundle_creator -quit -batchmode -executeMethod AssetBundleCreator.CreatePrefab -filename=cube -modelname=cube -extension=.fbx -colliders=cube_colliders.obj
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
(base) ➜  example_controllers git:(asset_bundle_creator_osx) ✗ ls ~/asset_bundle_creator/Assets/Resources/
cube.fbx           cube.mtl           cube_colliders.obj
```

Totally understand if this is low priority + difficult for you to debug without access to a mac. I'm just looking to recreate the `single_object` image dataset, so would disabling VHACD make this easier?

Thanks

**Comment by alters-mit** [comment] 2020-08-20 13:13
@normster To recreate the single_object dataset, you can indeed skip vhacd. In `AssetBundleCreator.create_prefab` you can specifiy the filename of the colliders file, which would typically be a subdivided version of the original .obj that VHACD creates. You can substitute that for any file though. When I created the dataset I used cube_colliders.obj for every single object.

Be aware though that there is some manual curation involved with ShapeNet SEM. Some of the models are lacking category labels, for example.

> Then I copied the output binary in ./test/Debug/testVHACD over to tdw/Python/tdw/binaries/Darwin/vhacd/testVHACD.

Could you please attach the binary to this thread?

> It looks like the called create_prefab command fails silently:

Run the test one more time. Then, please attach the [Editor log](https://docs.unity3d.com/Manual/LogFiles.html) to this thread.

**Comment by alters-mit** [comment] 2020-08-20 13:59
@normster Actually it seems like we might've gotten it to work! If you can, please run the following test to make sure that everything is working:

1. Delete `~/asset_bundle_creator/`
2. cd `/Users/normanmu/code/tdw/Python/tdw`
3. `git pull`
4. Run the test again.

>  I think mkdir -p /asset_bundle_creator/Assets/Resources/ is enough.

I think you were getting weird errors because this is not in fact enough... I had some placeholder files in all of the relevant directories in order to make sure that the directories would be created. However, the files were skipped over in OS X, possibly because they were empty. I added a bit of text into each of them now.

**Comment by normster** [comment] 2020-08-20 17:13
Which placeholder files do I need to create? I'm getting an assertion error when checking for ~/asset_bundle_creator now:

```
(base) ➜  example_controllers git:(asset_bundle_creator_osx) ✗ python3 local_object.py
Creating: /Users/normanmu/asset_bundle_creator
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
Traceback (most recent call last):
  File "local_object.py", line 45, in <module>
    LocalObject.run()
  File "local_object.py", line 18, in run
    asset_bundle_paths, record_path = AssetBundleCreator().create_asset_bundle("cube.fbx", True, 123, "", 1)
  File "/Users/normanmu/code/tdw/Python/tdw/asset_bundle_creator.py", line 68, in __init__
    self.project_path = self.get_unity_project()
  File "/Users/normanmu/code/tdw/Python/tdw/asset_bundle_creator.py", line 249, in get_unity_project
    assert unity_project_path.exists(), unity_project_path.resolve()
AssertionError: /Users/normanmu/asset_bundle_creator
```

**Comment by alters-mit** [comment] 2020-08-20 18:28
@normster This seems to be a problem related to your Unity license/credentials. I found this thread: https://forum.unity.com/threads/unity-wont-start-up-and-keeps-flashing.503993/

- Maybe see if there's something weird with your credentials? Try a new account? Check your firewall?
- Before re-running `local_object.py`, you should first delete `/Users/normanmu/asset_bundle_creator` if it exists (there may be an empty folder)
- This error indicates that there is something wrong with your firewall or credentials and will cause Unity to fail: `[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0`

Sorry I can't be more helpful than that; I haven't seen this problem before, and I don't think I'll be able to reproduce it on my end. If you figure this one out, please post the solution, so I can add it to our documentation.

**Comment by normster** [comment] 2020-08-20 18:53
Thanks, I realized I didn't have an active license. For those following along, I had to sign in to UnityHub and then navigate to the settings gear > License Management > Activate New License.

I had an issue with the list of platform strings since it looks like the default behavior is to generate the assets for all three. I passed in platforms=['osx'] to `prefab_to_asset_bundle` and added a similar parameter to `create_record` to only look for OSX resources.

Also, I re-installed tdw from source after changing the version numbers in version.py and setup.py to 1.6.5 instead of 1.6.6 because that was causing an issue with the build launch.

Looks like everything runs without an issue now!

```
(base) ➜  example_controllers git:(asset_bundle_creator_osx) ✗ python3 local_object.py
Creating: /Users/normanmu/asset_bundle_creator
2020-08-20 11:39:10.253 Unity[71344:10782024] Color LCD preferred device: AMD Radeon Pro 5300M (high power)
2020-08-20 11:39:10.253 Unity[71344:10782024] Metal devices available: 2
2020-08-20 11:39:10.253 Unity[71344:10782024] 0: AMD Radeon Pro 5300M (high power)
2020-08-20 11:39:10.253 Unity[71344:10782024] 1: Intel(R) UHD Graphics 630 (low power)
2020-08-20 11:39:10.254 Unity[71344:10782024] Using device AMD Radeon Pro 5300M (high power)
debugger-agent: Unable to listen on 21
Created new Unity project: /Users/normanmu/asset_bundle_creator
2020-08-20 11:39:38.784 Unity[71530:10783618] Color LCD preferred device: AMD Radeon Pro 5300M (high power)
2020-08-20 11:39:38.784 Unity[71530:10783618] Metal devices available: 2
2020-08-20 11:39:38.784 Unity[71530:10783618] 0: AMD Radeon Pro 5300M (high power)
2020-08-20 11:39:38.784 Unity[71530:10783618] 1: Intel(R) UHD Graphics 630 (low power)
2020-08-20 11:39:38.785 Unity[71530:10783618] Using device AMD Radeon Pro 5300M (high power)
verify_permissions --fix -- /Users/normanmu/asset_bundle_creator/Temp/Export Package/62e0c64b5590e4cbea6bbbd49628124b, running for normanmu
Done fixing - no errors
debugger-agent: Unable to listen on 29
Imported asset_bundle_creator.unitypackage into the new project.
Converting a .fbx file to .obj
Running V-HACD on a .obj file (this might take awhile).
Created: cube.wrl
Removed V-HACD log file.
Removed superfluous .obj file: cube.obj
Converting .wrl to .obj
Created /Users/normanmu/code/tdw/Python/example_controllers/cube_colliders.obj from .wrl file.
Copying files into the Unity project.
Copied files into the Unity project.
Creating the prefab...
2020-08-20 11:39:57.148 Unity[71702:10784871] Color LCD preferred device: AMD Radeon Pro 5300M (high power)
2020-08-20 11:39:57.148 Unity[71702:10784871] Metal devices available: 2
2020-08-20 11:39:57.148 Unity[71702:10784871] 0: AMD Radeon Pro 5300M (high power)
2020-08-20 11:39:57.148 Unity[71702:10784871] 1: Intel(R) UHD Graphics 630 (low power)
2020-08-20 11:39:57.150 Unity[71702:10784871] Using device AMD Radeon Pro 5300M (high power)
debugger-agent: Unable to listen on 29
Created the prefab.
Creating local asset bundles
2020-08-20 11:40:05.031 Unity[71706:10785229] Color LCD preferred device: AMD Radeon Pro 5300M (high power)
2020-08-20 11:40:05.031 Unity[71706:10785229] Metal devices available: 2
2020-08-20 11:40:05.031 Unity[71706:10785229] 0: AMD Radeon Pro 5300M (high power)
2020-08-20 11:40:05.031 Unity[71706:10785229] 1: Intel(R) UHD Graphics 630 (low power)
2020-08-20 11:40:05.032 Unity[71706:10785229] Using device AMD Radeon Pro 5300M (high power)
debugger-agent: Unable to listen on 29
Created local asset bundles.
Creating a record.
2020-08-20 11:40:15.802 Unity[71784:10786013] Color LCD preferred device: AMD Radeon Pro 5300M (high power)
2020-08-20 11:40:15.802 Unity[71784:10786013] Metal devices available: 2
2020-08-20 11:40:15.802 Unity[71784:10786013] 0: AMD Radeon Pro 5300M (high power)
2020-08-20 11:40:15.802 Unity[71784:10786013] 1: Intel(R) UHD Graphics 630 (low power)
2020-08-20 11:40:15.803 Unity[71784:10786013] Using device AMD Radeon Pro 5300M (high power)
debugger-agent: Unable to listen on 29
Wrote the record data to the disk.
Removed temporary files.
DONE!
Your installed tdw Python module is up to date with PyPi.
Python version is 1.6.5 but the build version is (unknown!).
Downloading version 1.6.5 of the build now...
Deleted old release.
Downloaded the build.
Saved the .zip file.
Extracted the .zip file to: /Users/normanmu/tdw_build
Deleted the .zip file.
Build version 1.6.5
Unity Engine 2019.2.21f1
Python tdw module version 1.6.5
```

The final output is a TDW/Unity window that looks like this:

<img width="258" alt="image" src="https://user-images.githubusercontent.com/6687910/90812748-6d701a80-e2db-11ea-9040-b70a836ef0c7.png">

**Comment by alters-mit** [comment] 2020-08-20 20:05
@normster Wonderful! I merged the branch into master. Thank you so much for your help!

I'm going to keep this keep this ticket up until we add Linux support to the AssetBundleCreator, but OS X support should work for everyone.

> For those following along,

[Added to our documentation.](https://github.com/threedworld-mit/tdw/blob/master/Documentation/misc_frontend/debug_tdw.md#warn-kq_init-detected-broken-kqueue-not-using-undefined-error-0)

> Also, I re-installed tdw from source after changing the version numbers in version.py and setup.py to 1.6.5 instead of 1.6.6 because that was causing an issue with the build launch.

The repo is ahead of the uploaded pip module; this will be resolved in a day or so.

**Comment by normster** [comment] 2020-08-20 20:13
Thank you for adding this so quickly! Happy to help :)

**Closed** 2020-11-10 20:06 UTC
