### ISSUE TITLE
single_object.py

### ISSUE THREAD

**Issue by BernhardEgger** [threedworld-mit/tdw#42] opened 2020-08-28 17:17 UTC
Hi,

I just got started with TDW and it so far looks all great :)

I have however three questions to the single-object case - this is probably closest to what we plan to do:
- it refers to "Martin Schrimpf's and Jonas Kubilius' ImageNet transfer research" is there a paper or something that shows me what that project was?
- it renders in the highest possible quality, but then saves the files in jpg format with strong compression artifacts - is that intended?
- I tried to start with --train=1 --val=1 and it seems like those values are just ignored?

Best
Bernhard

**Comment by alters-mit** [comment] 2020-08-28 18:29
> it refers to "Martin Schrimpf's and Jonas Kubilius' ImageNet transfer research" is there a paper or something that shows me what that project was?

I think this paper has the most information https://arxiv.org/pdf/2007.04954.pdf

> it renders in the highest possible quality, but then saves the files in jpg format with strong compression artifacts - is that intended?

Yes, because we found that they didn't affect the results. Use the `--screen_size` and `--output_size` parameters; if you set screen size to be higher (512) and output size lower (256) the image will be scaled down, which actually looks a lot better.

> I tried to start with --train=1 --val=1 and it seems like those values are just ignored?

How many images per category does the script generate?

**Comment by BernhardEgger** [comment] 2020-08-28 18:46
Thank you for guiding me for the paper

for the second point, I just deactivated the jpg output, since I'm generating pretty small images 

it generates more than one - I have to stop it so I don't know where it would go. This is the directory structure I get after few seconds:
└── images
    └── val
        └── n02774152
            ├── img_purse_0000.png
            ├── img_purse_0001.png
            ├── img_red_bag_0000.png
            ├── img_red_bag_0001.png
            ├── img_small_purse_0000.png
            ├── img_small_purse_0001.png
            ├── img_tan_purse_0000.png
            └── img_tan_purse_0001.png


the meta-data file however gets the correct value
    "train": 1,
    "val": 1,

**Comment by alters-mit** [comment] 2020-08-31 13:53
Closing this issue because this is the intended behavior of single_object.py

There should be one image _per model_. The fact that there's 2 is probably just a small rounding error.

**Closed by alters-mit** 2020-08-31 13:53 UTC
